FROM eclipse-temurin:17-jdk-alpine as BUILD
WORKDIR /server
# EXPOSE 8080
ADD . /server
RUN sed -i 's/\r$//' gradlew
RUN ./gradlew shadowJar --no-daemon

FROM eclipse-temurin:17-jdk-alpine as RUN
COPY --from=BUILD /server/build/libs/ktor-server.jar .
CMD ["java", "-jar", "ktor-server.jar"]
